language: node_js
node_js:
  - "0.10"
before_install: "sudo apt-get update && sudo apt-get install -y libcairo2-dev libjpeg8-dev libgif-dev optipng pngcrush pngquant libpango1.0-dev"
script: "npm run-script travis"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8480136ea087dfae1908
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
